#!/bin/sh

# Auto-install things for Mac
if [[ `uname` == "Darwin" ]]; then
	brew install pyenv
	brew install zsh-completions
fi

npm install -g spaceship-prompt

# Automatically moving the correct file for you, assuming default installation
cp ~/dev/focus/setup/Terminal/.zshrc ~/.zshrc
source ~/.zshrc
