version: "3.8"

services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual-server
    environment:
      - ACTUAL_SYNC_KEY=${ACTUAL_SYNC_KEY}
    volumes:
      - ${ACTUAL_DATA_DIR:-/data/actual}:/data
    ports:
      - "5006:5006"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.actual-server.rule=Host(`${ACTUAL_DOMAIN}`)"
      - "traefik.http.services.actual-server.loadbalancer.server.port=5006"
      - "traefik.http.routers.actual-server.entrypoints=https"
      - "traefik.http.routers.actual-server.tls=true"
      - "traefik.http.routers.actual-server.tls.certresolver=certchallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
