version: "3.8"

services:
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    environment:
      - ACTUAL_HOSTNAME=0.0.0.0
      - ACTUAL_PORT=${ACTUAL_PORT}
      - ACTUAL_SYNC_KEY=${ACTUAL_SYNC_KEY}
    volumes:
      - ${ACTUAL_DATA_DIR:-/data/actual}:/data
    ports:
      - "${ACTUAL_PORT}:5006"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.routers.actual.tls=true"
      - "traefik.http.routers.actual.tls.certresolver=letsencrypt"
      - "traefik.http.services.actual.loadbalancer.server.port=${ACTUAL_PORT}"
    networks:
      - proxy

networks:
  proxy:
    external: true
