api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # file:
  #   directory: "/"
  #   watch: true
  #   filename: "rules.toml"

certificatesResolvers:
  http:
    acme:
      email: some_email@email.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
