#!/bin/sh

# Instal Brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install required stuff
brew cask install visual-studio-code
brew install npm

# Then do setup things
./Terminal/setup
./Updates/setup
