version: "3"

services:
  gloomhaven_server:
    image: grepnull/gloomhaven-helper-headless:latest
    container_name: gloomhaven_server
    restart: always
    networks:
      - proxy
    ports:
      - 58887:58887/udp
      - 58888:58888
    volumes:
      - ${HOME}/Data/gloomhaven:/root/.ghh
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gloomhaven_server.entrypoints=http"
      - "traefik.http.routers.gloomhaven_server.rule=Host(${GHH_SERVER_DOMAIN})"
      - "traefik.http.routers.gloomhaven_server.middlewares=gloomhaven_server-https-redirect"
      - "traefik.http.middlewares.gloomhaven_server-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gloomhaven_server-secure.entrypoints=https"
      - "traefik.http.routers.gloomhaven_server-secure.rule=Host(${GHH_SERVER_DOMAIN})"
      - "traefik.http.routers.gloomhaven_server-secure.tls=true"
      - "traefik.http.routers.gloomhaven_server-secure.tls.certresolver=http"
      - "traefik.http.routers.gloomhaven_server-secure.service=gloomhaven_server"
      - "traefik.http.services.gloomhaven_server.loadbalancer.server.port=58888"

networks:
  proxy:
    external: true
